model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-aRa-aRa-aRa-
      s:
      - 0.499999982172
      - 3.99999985737
      - 2.99999995955
      - 2.50000001064
      - 2.99999995955
      - 3.99999985737
      - 99.9999923183
      nd:
      - 1.62000000477
      - 1.72000002861
      - 1.62000000477
      vd:
      - 60.0
      - 30.0
      - 60.0
      c:
      - 0.010080645442
      - -0.010080645442
      - -0.0104166669846
      - 0.0104166669846
      - 0.010080645442
      - -0.0101024396716
      a:
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      d: []
      m: []
      nominal_wavelength: 550.0
      dpgf: null
      z: []
      misc_surface_model: null
      bezier_aspherics: false
      target_efl: 100.0
      solve_type: focal_length
      solve_idx: null
      paraxial_image_solve: false
      total_track_length_solve: null
      qc_vars: false
      glass_file: configs/moldable_materials.csv
      scale_factor: 17.857142857142858
