model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-aRa-
      s:
      - 0.49857323308
      - 15.0017602413
      - 93.3283269065
      c:
      - 0.014523526158
      - -0.00443442456541
      nd:
      - 1.53510433771
      vd:
      - 58.9199428701
      a:
      - - 0.0
        - -3.33929859754e-06
        - 4.29130439104e-08
        - 2.49271151062e-10
        - -1.38591635969e-11
      - - 0.0
        - 3.31328774825e-06
        - -8.6654840598e-08
        - -7.8643465514e-10
        - 2.34833089281e-11
      d: []
      m: []
      z: []
      nominal_wavelength: 550.0
      target_efl: 100.0
      solve_type: focal_length
      solve_idx: 1
      paraxial_image_solve: true
      total_track_length_solve: null
      qc_vars: false
      scale_factor: 6.25
      bezier_aspherics: false
      glass_file: configs/moldable_materials.csv
      misc_surface_model: null
