model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-aRz-aRa-
      s:
      - 0.5
      - 3.0
      - 20.0
      - 3.0
      - 100.0
      c:
      - 0.0
      - -0.008283160948776722
      - 0.004166666666666666
      - -0.004166666666666666
      nd:
      - 1.6
      - 1.6
      vd:
      - 35.0
      - 35.0
      a:
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      d: []
      m: []
      z:
      - - - 0.0
          - 0.0
          - 0.0
          - 2.097617696340303
        - - 0.0
          - 0.0
          - 0.018222954087308788
          - 2.966479394838265
        - - 0.0
          - 0.0
          - 0.036445908174617576
          - 3.63318042491699
        - - 0.0
          - 0.0
          - 0.05466886226192637
          - 4.195235392680606
        - - 0.0
          - 0.0
          - 0.07289181634923515
          - 4.690415759823429
        - - 0.0
          - 0.0
          - 0.09111477043654394
          - 5.138093031466052
        - - 0.0
          - 0.0
          - 0.10933772452385274
          - 5.5497747702046425
        - - 0.0
          - 0.0
          - 0.12756067861116152
          - 5.93295878967653
        - - 0.0
          - 0.0
          - 0.1457836326984703
          - 6.25
      nominal_wavelength: 550.0
      target_efl: 100.0
      solve_type: focal_length
      solve_idx: 3
      paraxial_image_solve: true
      total_track_length_solve: null
      qc_vars: false
      scale_factor: 6.25
      bezier_aspherics: false
      glass_file: configs/moldable_materials.csv
      misc_surface_model: null
