model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-aRz-aRa-
      s:
      - 0.5
      - 3.0
      - 20.0
      - 3.0
      - 100.0
      c:
      - 0.0
      - -0.008283160948776722
      - 0.004166666666666666
      - -0.004166666666666666
      nd:
      - 1.6
      - 1.6
      vd:
      - 35.0
      - 35.0
      a:
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      d: []
      m: []
      z:
      - - - 0.0
          - 0.0
          - 0.0
          - 3.1464265445104544
        - - 0.0
          - 0.0
          - 0.04100164669644477
          - 4.449719092257397
        - - 0.0
          - 0.0
          - 0.08200329339288955
          - 5.449770637375485
        - - 0.0
          - 0.0
          - 0.12300494008933432
          - 6.25
      nominal_wavelength: 550.0
      target_efl: 100.0
      solve_type: focal_length
      solve_idx: 3
      paraxial_image_solve: true
      total_track_length_solve: null
      qc_vars: false
      scale_factor: 6.25
      bezier_aspherics: false
      glass_file: configs/moldable_materials.csv
      misc_surface_model: null
