model:
  lens_parameterization:
    init_args:
      freeze:
        s: true
        c: true
        g: true
        m: true
        d: true
        a:
        - - true
          - false
          - false
          - false
          - false
        z:
        - - - false
            - false
            - true
            - true
  residuals:
  - class_path: eisoptx.optimization.residuals.TransverseRayAberrationResiduals
    init_args:
      weight: 1.0
  lens_optimizer:
    class_path: eisoptx.optimization.optimizers.LMOptimizer
    init_args:
      lm_parameter: 1.0
      damped_term_min: 1.0e-06
      tolerance: 1.0
      lam_increase_factor: 4.0
      lam_decrease_factor: 2.0
      lam_eps: 1.0e-10
      beta: 0.95
trainer:
  log_every_n_steps: 1
  check_val_every_n_epoch: null
  callbacks:
  - class_path: eisoptx.utils.callbacks.ConfigFileCallback
    init_args:
      every_n_steps: 20
  - eisoptx.main.CustomProgressBar
