model:
  ray_initialization:
    init_args:
      pupil_sampling_mode: skew_uniform
data:
  init_args:
    n_samples: 1
trainer:
  callbacks:
    - class_path: eisoptx.utils.visualization.VisualizationCallback
      init_args:
        every_n_steps: 1
        visualizations:
          - class_path: eisoptx.utils.visualization.LensLayout
            init_args:
              wavelengths: [486.1, 550., 656.3]
              n_fields: 3
              n_rays: 21
          - class_path: eisoptx.utils.visualization.SpotDiagrams
            init_args:
              field_indices: [0, 1, 2]
        save_formats: [png]
        rc_params:
          figure.figsize: '7.0, 3.0'
          figure.constrained_layout.use: 'True'
          figure.dpi: '200'
          font.size: '7'
          lines.linewidth: '0.35'
