model:
  ray_initialization:
    init_args:
      pupil_sampling_mode: skew_uniform_zonal
      pupil_sampling_kwargs:
        n_r: 100
        n_theta: 32
  lens_parameterization:
    init_args:
      freeze:
        s:
        - false
        - false
        - false
        - false
        - false
        - false
        - false
        - false
        - true
        c:
        - false
        - false
        - false
        - false
        - false
        - false
        - false
        - false
        g: false
        m: true
        d: true
        a:
        - - true
          - false
          - false
          - false
          - false
        z: true
trainer:
  log_every_n_steps: 1
  check_val_every_n_epoch: null
  callbacks:
  - eisoptx.utils.callbacks.ExtendedLoggingCallback
  - class_path: eisoptx.utils.callbacks.CodeVSeqFileCallback
    init_args:
      use_private_catalog: true
  - class_path: eisoptx.utils.callbacks.ConfigFileCallback
    init_args:
      every_n_steps: 250
  - eisoptx.main.CustomProgressBar
  - class_path: ModelCheckpoint
    init_args:
      every_n_train_steps: 100
  - class_path: eisoptx.utils.callbacks.IncreaseGlassVariableResidualsWeightCallback
    init_args:
      initial_step: 0.0
      final_step: 0.5
      n_increments: 25
      initial_weight: 1.525878e-05
      final_weight: 512
  - class_path: eisoptx.utils.callbacks.ToggleGlassOptimizationCallback
    init_args:
      initial_step: 0.0
      final_step: 0.5
      n_cycles: 25
  - class_path: eisoptx.utils.callbacks.BindMaterialsCallback
    init_args:
      step: 0.5
